; PlatformIO Project Configuration File

[platformio]
default_envs = esp32

[env]
build_unflags = -std=gnu++2a -std=gnu++2b -Werror=reorder
build_flags =
    -std=gnu++20
    -mtext-section-literals
build_src_flags =
    -Wall
    -Werror

[env:esp32]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.03/platform-espressif32.zip
;platform = espressif32 @ 6.12.0
board = lolin32
framework = arduino
;board_build.partitions = no_ota.csv  ; no plans for OTA anyway, so just reclaim some space

lib_deps =
    EEPROM
    etlcpp/Embedded Template Library @ ~20.47
    tzapu/WiFiManager @ ^2.0.17
;    ESP32Async/AsyncTCP @ ^3.4.10
;    olikraus/U8g2 @ ^2.36.18

monitor_filters = esp32_exception_decoder
monitor_speed = 115200
