; PlatformIO Project Configuration File

[platformio]
default_envs = esp32

[env]
build_unflags = -std=gnu++2a -std=gnu++2b -Werror=reorder
build_flags =
    -std=gnu++20
    -mtext-section-literals
    -Iinclude
    -DLV_CONF_INCLUDE_SIMPLE
build_src_flags =
    -Wall
    -Werror
    -Wno-deprecated-enum-enum-conversion

[env:esp32]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.03/platform-espressif32.zip
;platform = espressif32 @ 6.12.0
board = lolin32
framework = arduino
board_build.partitions = no_ota.csv  ; no plans for OTA anyway, so just reclaim some space

lib_deps =
    EEPROM
    etlcpp/Embedded Template Library @ ~20.47
    tzapu/WiFiManager @ ^2.0.17
    ; flash62au/WiThrottleProtocol @ ^1.1.27
    lvgl/lvgl@~9.5.0
;    ESP32Async/AsyncTCP @ ^3.4.10
;    olikraus/U8g2 @ ^2.36.18

monitor_filters = esp32_exception_decoder
monitor_speed = 115200

# build with PS: $env:Path = 'C:\msys64\ucrt64\bin;' + $env:Path; <path-to-pio>\pio.exe run -e native -j 8
# run with .\.pio\build\native\program.exe
[env:native]
platform = platformio/native@1.2.1
extra_scripts =
    pre:src_native/native_extra.py
lib_deps =
    etlcpp/Embedded Template Library @ ~20.47
    lvgl/lvgl@~9.5.0
build_src_filter =
    +<ui/>
    +<network/ServerDiscovery.cpp>
build_unflags =
    -mtext-section-literals
build_flags =
    -std=c++20
    -Isrc_native
    -Isrc_native/mocks
    -Iinclude
    -Isrc
    -DLV_CONF_INCLUDE_SIMPLE
    -luser32
    -lgdi32
build_src_flags =
    -Wall
    -Werror
