/* Generated by json_to_lvgl.py. */
#include "lvgl.h"

static const uint8_t glyph_bitmap[] = {
    /* U+0020 " " */

    /* U+0021 "!" */
    0xC0, 0xC0, 0xC0, 0xC0, 0xC0, 0x00, 0xC0,

    /* U+0022 "\"" */
    0xA0, 0xA0,

    /* U+0023 "#" */
    0x50, 0xF8, 0xF8, 0x50, 0xF8, 0xF8, 0x50,

    /* U+0024 "$" */
    0x50, 0x78, 0xD0, 0xF0, 0x78, 0x58, 0xF0, 0x50,

    /* U+0025 "%" */
    0xC8, 0xD8, 0x10, 0x30, 0x20, 0x6C, 0x4C,

    /* U+0026 "&" */
    0x70, 0xD8, 0x70, 0xF4, 0xDC, 0xDC, 0x74,

    /* U+0027 "'" */
    0x80, 0x80,

    /* U+0028 "(" */
    0x20, 0x40, 0xC0, 0xC0, 0xC0, 0xC0, 0x40, 0x20,

    /* U+0029 ")" */
    0x80, 0x40, 0x60, 0x60, 0x60, 0x60, 0x40, 0x80,

    /* U+002A "*" */
    0x20, 0xA8, 0xF8, 0x70, 0xF8, 0xA8, 0x20,

    /* U+002B "+" */
    0x20, 0x20, 0xF8, 0x20, 0x20,

    /* U+002C "," */
    0x40, 0xC0, 0x80,

    /* U+002D "-" */
    0xF0,

    /* U+002E "." */
    0xC0, 0xC0,

    /* U+002F "/" */
    0x20, 0x20, 0x60, 0x40, 0xC0, 0x80, 0x80,

    /* U+0030 "0" */
    0x70, 0xD8, 0xD8, 0xD8, 0xD8, 0xD8, 0x70,

    /* U+0031 "1" */
    0x60, 0xE0, 0x60, 0x60, 0x60, 0x60, 0x60,

    /* U+0032 "2" */
    0xF0, 0x18, 0x18, 0x70, 0xC0, 0xC0, 0xF8,

    /* U+0033 "3" */
    0xF0, 0x18, 0x18, 0x70, 0x18, 0x18, 0xF0,

    /* U+0034 "4" */
    0x18, 0x38, 0x58, 0x98, 0xF8, 0x18, 0x18,

    /* U+0035 "5" */
    0xF0, 0x80, 0xF0, 0x18, 0x18, 0x18, 0xF0,

    /* U+0036 "6" */
    0x70, 0xC0, 0xF0, 0xD8, 0xD8, 0xD8, 0x70,

    /* U+0037 "7" */
    0xF8, 0x18, 0x30, 0x30, 0x60, 0x60, 0x60,

    /* U+0038 "8" */
    0x70, 0xD8, 0xD8, 0x70, 0xD8, 0xD8, 0x70,

    /* U+0039 "9" */
    0x70, 0xD8, 0xD8, 0xD8, 0x78, 0x18, 0x70,

    /* U+003A ":" */
    0xC0, 0xC0, 0x00, 0xC0, 0xC0,

    /* U+003B ";" */
    0xC0, 0xC0, 0x00, 0x40, 0xC0, 0x80,

    /* U+003C "<" */
    0x10, 0x30, 0x60, 0xC0, 0x60, 0x30, 0x10,

    /* U+003D "=" */
    0xF0, 0x00, 0xF0,

    /* U+003E ">" */
    0x80, 0xC0, 0x60, 0x30, 0x60, 0xC0, 0x80,

    /* U+003F "?" */
    0xF0, 0x18, 0x30, 0x60, 0x60, 0x00, 0x60,

    /* U+0040 "@" */
    0x78, 0xCC, 0xFC, 0xDC, 0xFC, 0xC0, 0x78,

    /* U+0041 "A" */
    0x70, 0xD8, 0xD8, 0xD8, 0xF8, 0xD8, 0xD8,

    /* U+0042 "B" */
    0xF0, 0xD8, 0xF0, 0xD8, 0xD8, 0xD8, 0xF0,

    /* U+0043 "C" */
    0x78, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0, 0x78,

    /* U+0044 "D" */
    0xF0, 0xD8, 0xD8, 0xD8, 0xD8, 0xD8, 0xF0,

    /* U+0045 "E" */
    0xF8, 0xC0, 0xF0, 0xC0, 0xC0, 0xC0, 0xF8,

    /* U+0046 "F" */
    0xF8, 0xC0, 0xF0, 0xC0, 0xC0, 0xC0, 0xC0,

    /* U+0047 "G" */
    0x70, 0xC0, 0xC0, 0xD8, 0xD8, 0xD8, 0x78,

    /* U+0048 "H" */
    0xD8, 0xD8, 0xF8, 0xD8, 0xD8, 0xD8, 0xD8,

    /* U+0049 "I" */
    0xC0, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0,

    /* U+004A "J" */
    0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0xE0,

    /* U+004B "K" */
    0xCC, 0xD8, 0xF0, 0xE0, 0xF0, 0xD8, 0xCC,

    /* U+004C "L" */
    0xC0, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0, 0xF0,

    /* U+004D "M" */
    0x82, 0xC6, 0xEE, 0xFE, 0xD6, 0xC6, 0xC6,

    /* U+004E "N" */
    0x8C, 0xCC, 0xEC, 0xFC, 0xDC, 0xCC, 0xC4,

    /* U+004F "O" */
    0x78, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0x78,

    /* U+0050 "P" */
    0xF0, 0xD8, 0xD8, 0xD8, 0xF0, 0xC0, 0xC0,

    /* U+0051 "Q" */
    0x78, 0xCC, 0xCC, 0xCC, 0xCC, 0xDC, 0x78, 0x0C,

    /* U+0052 "R" */
    0xF0, 0xD8, 0xD8, 0xD8, 0xF0, 0xD0, 0xD8,

    /* U+0053 "S" */
    0x70, 0xC0, 0xC0, 0x60, 0x30, 0x30, 0xE0,

    /* U+0054 "T" */
    0xFC, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30,

    /* U+0055 "U" */
    0xD8, 0xD8, 0xD8, 0xD8, 0xD8, 0xD8, 0x70,

    /* U+0056 "V" */
    0xCC, 0xCC, 0xCC, 0x78, 0x78, 0x30, 0x30,

    /* U+0057 "W" */
    0xC6, 0xC6, 0xD6, 0xFE, 0x7C, 0x7C, 0x6C,

    /* U+0058 "X" */
    0xCC, 0xCC, 0x78, 0x30, 0x78, 0xCC, 0xCC,

    /* U+0059 "Y" */
    0xCC, 0xCC, 0x78, 0x30, 0x30, 0x30, 0x30,

    /* U+005A "Z" */
    0xF8, 0x18, 0x38, 0x70, 0xE0, 0xC0, 0xF8,

    /* U+005B "[" */
    0xE0, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0, 0xE0,

    /* U+005C "\\" */
    0x80, 0x80, 0xC0, 0x40, 0x60, 0x20, 0x20,

    /* U+005D "]" */
    0xE0, 0x60, 0x60, 0x60, 0x60, 0x60, 0x60, 0xE0,

    /* U+005E "^" */
    0x40, 0xE0, 0xA0,

    /* U+005F "_" */
    0xFC,

    /* U+0060 "`" */
    0x80, 0x40,

    /* U+0061 "a" */
    0x70, 0x18, 0x78, 0xD8, 0x78,

    /* U+0062 "b" */
    0xC0, 0xC0, 0xF0, 0xD8, 0xD8, 0xD8, 0xF0,

    /* U+0063 "c" */
    0x70, 0xC0, 0xC0, 0xC0, 0x70,

    /* U+0064 "d" */
    0x18, 0x18, 0x78, 0xD8, 0xD8, 0xD8, 0x78,

    /* U+0065 "e" */
    0x70, 0xD8, 0xF8, 0xC0, 0x78,

    /* U+0066 "f" */
    0x60, 0xC0, 0xE0, 0xC0, 0xC0, 0xC0, 0xC0,

    /* U+0067 "g" */
    0x78, 0xD8, 0xD8, 0x78, 0x18, 0x70,

    /* U+0068 "h" */
    0xC0, 0xC0, 0xF0, 0xD8, 0xD8, 0xD8, 0xD8,

    /* U+0069 "i" */
    0xC0, 0x00, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0,

    /* U+006A "j" */
    0x60, 0x00, 0x60, 0x60, 0x60, 0x60, 0x60, 0xC0,

    /* U+006B "k" */
    0xC0, 0xC0, 0xD8, 0xF0, 0xE0, 0xF0, 0xD8,

    /* U+006C "l" */
    0xC0, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0,

    /* U+006D "m" */
    0xFE, 0xDB, 0xDB, 0xDB, 0xDB,

    /* U+006E "n" */
    0xF0, 0xD8, 0xD8, 0xD8, 0xD8,

    /* U+006F "o" */
    0x70, 0xD8, 0xD8, 0xD8, 0x70,

    /* U+0070 "p" */
    0xF0, 0xD8, 0xD8, 0xF0, 0xC0, 0xC0,

    /* U+0071 "q" */
    0x78, 0xD8, 0xD8, 0x78, 0x18, 0x18,

    /* U+0072 "r" */
    0xD0, 0xF0, 0xC0, 0xC0, 0xC0,

    /* U+0073 "s" */
    0x70, 0xC0, 0xF0, 0x30, 0xE0,

    /* U+0074 "t" */
    0xC0, 0xC0, 0xE0, 0xC0, 0xC0, 0xC0, 0x60,

    /* U+0075 "u" */
    0xD8, 0xD8, 0xD8, 0xD8, 0x78,

    /* U+0076 "v" */
    0xD8, 0xD8, 0x70, 0x70, 0x20,

    /* U+0077 "w" */
    0xC6, 0xD6, 0xD6, 0x7C, 0x6C,

    /* U+0078 "x" */
    0xD8, 0xD8, 0x70, 0xD8, 0xD8,

    /* U+0079 "y" */
    0xD8, 0xD8, 0xD8, 0x78, 0x18, 0x70,

    /* U+007A "z" */
    0xF8, 0x30, 0x60, 0xC0, 0xF8,

    /* U+007B "{" */
    0xE0, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0, 0xE0,

    /* U+007C "|" */
    0xC0, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0,

    /* U+007D "}" */
    0xE0, 0x60, 0x60, 0x60, 0x60, 0x60, 0x60, 0xE0,

    /* U+007E "~" */
    0x68, 0xB0,

    /* U+00A0 " " */

    /* U+00A1 "¡" */
    0xC0, 0x00, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0,

    /* U+00A3 "£" */
    0x38, 0x60, 0x60, 0x60, 0xF0, 0x60, 0xF8,

    /* U+00A4 "¤" */
    0x88, 0x70, 0xD8, 0xD8, 0x70, 0x88,

    /* U+00A5 "¥" */
    0xCC, 0x78, 0xFC, 0x30, 0xFC, 0x30, 0x30,

    /* U+00A6 "¦" */
    0xC0, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0,

    /* U+00A7 "§" */
    0x60, 0xD0, 0xE0, 0xB0, 0xD0, 0x70, 0xB0, 0x60,

    /* U+00BA "º" */
    0x40, 0xA0, 0x40, 0x00, 0xE0,

    /* U+00BF "¿" */
    0x30, 0x00, 0x30, 0x30, 0x60, 0xC0, 0x78,

    /* U+00C0 "À" */
    0x40, 0x20, 0x70, 0xD8, 0xF8, 0xD8, 0xD8,

    /* U+00C1 "Á" */
    0x10, 0x20, 0x70, 0xD8, 0xF8, 0xD8, 0xD8,

    /* U+00C2 "Â" */
    0x20, 0x50, 0xF8, 0xD8, 0xF8, 0xD8, 0xD8,

    /* U+00C3 "Ã" */
    0x68, 0xB0, 0x70, 0xD8, 0xF8, 0xD8, 0xD8,

    /* U+00C4 "Ä" */
    0x50, 0x00, 0x70, 0xD8, 0xF8, 0xD8, 0xD8,

    /* U+00C5 "Å" */
    0x20, 0x50, 0x70, 0xD8, 0xF8, 0xD8, 0xD8,

    /* U+00C6 "Æ" */
    0x3E, 0x78, 0xD8, 0xFC, 0xD8, 0xD8, 0xDE,

    /* U+00C7 "Ç" */
    0x78, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0, 0x78, 0x20,

    /* U+00C8 "È" */
    0x40, 0x20, 0xF8, 0xC0, 0xF0, 0xC0, 0xF8,

    /* U+00C9 "É" */
    0x10, 0x20, 0xF8, 0xC0, 0xF0, 0xC0, 0xF8,

    /* U+00CA "Ê" */
    0x20, 0x50, 0xF8, 0xC0, 0xF0, 0xC0, 0xF8,

    /* U+00CB "Ë" */
    0x50, 0x00, 0xF8, 0xC0, 0xF0, 0xC0, 0xF8,

    /* U+00CC "Ì" */
    0x80, 0x40, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0,

    /* U+00CD "Í" */
    0x40, 0x80, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0,

    /* U+00CE "Î" */
    0x40, 0xA0, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0,

    /* U+00CF "Ï" */
    0xA0, 0x00, 0x60, 0x60, 0x60, 0x60, 0x60,

    /* U+00D1 "Ñ" */
    0x68, 0xB0, 0x98, 0xD8, 0xF8, 0xD8, 0xC8,

    /* U+00D2 "Ò" */
    0x20, 0x10, 0x78, 0xCC, 0xCC, 0xCC, 0x78,

    /* U+00D3 "Ó" */
    0x10, 0x20, 0x78, 0xCC, 0xCC, 0xCC, 0x78,

    /* U+00D4 "Ô" */
    0x30, 0x48, 0xFC, 0xCC, 0xCC, 0xCC, 0x78,

    /* U+00D5 "Õ" */
    0x34, 0x58, 0x78, 0xCC, 0xCC, 0xCC, 0x78,

    /* U+00D6 "Ö" */
    0x48, 0x00, 0x78, 0xCC, 0xCC, 0xCC, 0x78,

    /* U+00D8 "Ø" */
    0x7C, 0xCC, 0xDC, 0xFC, 0xEC, 0xCC, 0xF8,

    /* U+00D9 "Ù" */
    0x40, 0x20, 0xD8, 0xD8, 0xD8, 0xD8, 0x70,

    /* U+00DA "Ú" */
    0x10, 0x20, 0xD8, 0xD8, 0xD8, 0xD8, 0x70,

    /* U+00DB "Û" */
    0x20, 0x50, 0xD8, 0xD8, 0xD8, 0xD8, 0x70,

    /* U+00DC "Ü" */
    0x50, 0x00, 0xD8, 0xD8, 0xD8, 0xD8, 0x70,

    /* U+00DD "Ý" */
    0x08, 0x10, 0xCC, 0x78, 0x30, 0x30, 0x30,

    /* U+00DF "ß" */
    0x70, 0xD8, 0xF0, 0xD8, 0xD8, 0xD8, 0xD0, 0xC0,

    /* U+00E0 "à" */
    0x20, 0x10, 0x70, 0x18, 0x78, 0xD8, 0x78,

    /* U+00E1 "á" */
    0x10, 0x20, 0x70, 0x18, 0x78, 0xD8, 0x78,

    /* U+00E2 "â" */
    0x20, 0x50, 0xF8, 0x18, 0x78, 0xD8, 0x78,

    /* U+00E3 "ã" */
    0x68, 0xB0, 0x70, 0x18, 0x78, 0xD8, 0x78,

    /* U+00E4 "ä" */
    0x50, 0x00, 0x70, 0x18, 0x78, 0xD8, 0x78,

    /* U+00E5 "å" */
    0x20, 0x50, 0x78, 0x18, 0x78, 0xD8, 0x78,

    /* U+00E6 "æ" */
    0x7C, 0x1A, 0x7E, 0xD8, 0x7E,

    /* U+00E7 "ç" */
    0x70, 0xC0, 0xC0, 0xC0, 0x70, 0x20,

    /* U+00E8 "è" */
    0x40, 0x20, 0x70, 0xD8, 0xF8, 0xC0, 0x78,

    /* U+00E9 "é" */
    0x10, 0x20, 0x70, 0xD8, 0xF8, 0xC0, 0x78,

    /* U+00EA "ê" */
    0x20, 0x50, 0xF8, 0xD8, 0xF8, 0xC0, 0x78,

    /* U+00EB "ë" */
    0x50, 0x00, 0x70, 0xD8, 0xF8, 0xC0, 0x78,

    /* U+00EC "ì" */
    0x80, 0x40, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0,

    /* U+00ED "í" */
    0x40, 0x80, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0,

    /* U+00EE "î" */
    0x40, 0xA0, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0,

    /* U+00EF "ï" */
    0xA0, 0x00, 0x60, 0x60, 0x60, 0x60, 0x60,

    /* U+00F1 "ñ" */
    0x68, 0xB0, 0xF0, 0xD8, 0xD8, 0xD8, 0xD8,

    /* U+00F2 "ò" */
    0x40, 0x20, 0x70, 0xD8, 0xD8, 0xD8, 0x70,

    /* U+00F3 "ó" */
    0x10, 0x20, 0x70, 0xD8, 0xD8, 0xD8, 0x70,

    /* U+00F4 "ô" */
    0x20, 0x50, 0xF8, 0xD8, 0xD8, 0xD8, 0x70,

    /* U+00F5 "õ" */
    0x68, 0xB0, 0x70, 0xD8, 0xD8, 0xD8, 0x70,

    /* U+00F6 "ö" */
    0x50, 0x00, 0x70, 0xD8, 0xD8, 0xD8, 0x70,

    /* U+00F8 "ø" */
    0x78, 0xD8, 0xF8, 0xD8, 0xF0,

    /* U+00F9 "ù" */
    0x40, 0x20, 0xD8, 0xD8, 0xD8, 0xD8, 0x78,

    /* U+00FA "ú" */
    0x10, 0x20, 0xD8, 0xD8, 0xD8, 0xD8, 0x78,

    /* U+00FB "û" */
    0x20, 0x50, 0xD8, 0xD8, 0xD8, 0xD8, 0x78,

    /* U+00FC "ü" */
    0x50, 0x00, 0xD8, 0xD8, 0xD8, 0xD8, 0x78,

    /* U+00FD "ý" */
    0x10, 0x20, 0xD8, 0xD8, 0xD8, 0x78, 0x18, 0x70,

    /* U+00FF "ÿ" */
    0x50, 0x00, 0xD8, 0xD8, 0xD8, 0x78, 0x18, 0x70,
};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 0, .adv_w = 48, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 0, .adv_w = 48, .box_w = 2, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 7, .adv_w = 64, .box_w = 3, .box_h = 2, .ofs_x = 0, .ofs_y = 5},
    {.bitmap_index = 9, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 16, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 24, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 31, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 38, .adv_w = 32, .box_w = 1, .box_h = 2, .ofs_x = 0, .ofs_y = 5},
    {.bitmap_index = 40, .adv_w = 64, .box_w = 3, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 48, .adv_w = 64, .box_w = 3, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 56, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 63, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 1},
    {.bitmap_index = 68, .adv_w = 48, .box_w = 2, .box_h = 3, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 71, .adv_w = 80, .box_w = 4, .box_h = 1, .ofs_x = 0, .ofs_y = 3},
    {.bitmap_index = 72, .adv_w = 48, .box_w = 2, .box_h = 2, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 74, .adv_w = 64, .box_w = 3, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 81, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 88, .adv_w = 64, .box_w = 3, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 95, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 102, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 109, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 116, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 123, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 130, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 137, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 144, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 151, .adv_w = 48, .box_w = 2, .box_h = 5, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 156, .adv_w = 48, .box_w = 2, .box_h = 6, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 162, .adv_w = 80, .box_w = 4, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 169, .adv_w = 80, .box_w = 4, .box_h = 3, .ofs_x = 0, .ofs_y = 1},
    {.bitmap_index = 172, .adv_w = 80, .box_w = 4, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 179, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 186, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 193, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 200, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 207, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 214, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 221, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 228, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 235, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 242, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 249, .adv_w = 48, .box_w = 2, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 256, .adv_w = 80, .box_w = 4, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 263, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 270, .adv_w = 80, .box_w = 4, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 277, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 284, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 291, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 298, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 305, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 313, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 320, .adv_w = 80, .box_w = 4, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 327, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 334, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 341, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 348, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 355, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 362, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 369, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 376, .adv_w = 64, .box_w = 3, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 384, .adv_w = 64, .box_w = 3, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 391, .adv_w = 64, .box_w = 3, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 399, .adv_w = 64, .box_w = 3, .box_h = 3, .ofs_x = 0, .ofs_y = 4},
    {.bitmap_index = 402, .adv_w = 96, .box_w = 6, .box_h = 1, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 403, .adv_w = 48, .box_w = 2, .box_h = 2, .ofs_x = 0, .ofs_y = 5},
    {.bitmap_index = 405, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 410, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 417, .adv_w = 80, .box_w = 4, .box_h = 5, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 422, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 429, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 434, .adv_w = 64, .box_w = 3, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 441, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 447, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 454, .adv_w = 48, .box_w = 2, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 461, .adv_w = 64, .box_w = 3, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 469, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 476, .adv_w = 48, .box_w = 2, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 483, .adv_w = 144, .box_w = 8, .box_h = 5, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 488, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 493, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 498, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 504, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 510, .adv_w = 80, .box_w = 4, .box_h = 5, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 515, .adv_w = 80, .box_w = 4, .box_h = 5, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 520, .adv_w = 64, .box_w = 3, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 527, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 532, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 537, .adv_w = 128, .box_w = 7, .box_h = 5, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 542, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 547, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 553, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 558, .adv_w = 64, .box_w = 3, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 566, .adv_w = 48, .box_w = 2, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 574, .adv_w = 64, .box_w = 3, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 582, .adv_w = 96, .box_w = 5, .box_h = 2, .ofs_x = 0, .ofs_y = 5},
    {.bitmap_index = 584, .adv_w = 48, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 584, .adv_w = 48, .box_w = 2, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 591, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 598, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 604, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 611, .adv_w = 48, .box_w = 2, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 619, .adv_w = 80, .box_w = 4, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 627, .adv_w = 64, .box_w = 3, .box_h = 5, .ofs_x = 0, .ofs_y = 2},
    {.bitmap_index = 632, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 639, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 646, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 653, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 660, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 667, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 674, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 681, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 688, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 696, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 703, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 710, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 717, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 724, .adv_w = 48, .box_w = 2, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 731, .adv_w = 48, .box_w = 2, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 738, .adv_w = 64, .box_w = 3, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 745, .adv_w = 64, .box_w = 3, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 752, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 759, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 766, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 773, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 780, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 787, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 794, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 801, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 808, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 815, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 822, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 829, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 836, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 844, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 851, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 858, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 865, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 872, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 879, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 886, .adv_w = 128, .box_w = 7, .box_h = 5, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 891, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 897, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 904, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 911, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 918, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 925, .adv_w = 48, .box_w = 2, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 932, .adv_w = 48, .box_w = 2, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 939, .adv_w = 64, .box_w = 3, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 946, .adv_w = 64, .box_w = 3, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 953, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 960, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 967, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 974, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 981, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 988, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 995, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1000, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1007, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1014, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1021, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1028, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 1036, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
};



static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {
        .range_start = 32, .range_length = 95, .glyph_id_start = 1,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    },
    {
        .range_start = 160, .range_length = 2, .glyph_id_start = 96,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    },
    {
        .range_start = 163, .range_length = 5, .glyph_id_start = 98,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    },
    {
        .range_start = 186, .range_length = 1, .glyph_id_start = 103,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    },
    {
        .range_start = 191, .range_length = 17, .glyph_id_start = 104,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    },
    {
        .range_start = 209, .range_length = 6, .glyph_id_start = 121,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    },
    {
        .range_start = 216, .range_length = 6, .glyph_id_start = 127,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    },
    {
        .range_start = 223, .range_length = 17, .glyph_id_start = 133,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    },
    {
        .range_start = 241, .range_length = 6, .glyph_id_start = 150,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    },
    {
        .range_start = 248, .range_length = 6, .glyph_id_start = 156,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    },
    {
        .range_start = 255, .range_length = 1, .glyph_id_start = 162,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    }
};

static const lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 11,
    .bpp = 1,
    .kern_classes = 0,
    .bitmap_format = LV_FONT_FMT_TXT_PLAIN,
    .stride = 1
};

const lv_font_t u8g2_font_nokiafc22_tf = {
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 8,
    .base_line = 1,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -1,
    .underline_thickness = 1,
    .dsc = &font_dsc,
    .fallback = NULL,
    .user_data = NULL
};
